import { Story } from '../../types/story';
import { buildSegment } from '../story-helpers';

export const hareAndTortoiseStory: Story = {
  id: 'hare-and-tortoise',
  slug: 'hare-and-tortoise',
  title: 'ಮೊಲ ಮತ್ತು ಆಮೆ',
  sourceTitle: 'The Hare and the Tortoise',
  sourceLabel: 'Aesop • Familiar Story',
  level: 'Beginner',
  estimatedMinutes: 3,
  summary: 'A familiar race story that lets learners follow simple action words, animal names, and pace-related vocabulary.',
  corpus: 'Aesop',
  themeTags: ['animals', 'perseverance', 'pace'],
  grammarFocus: ['simple past', 'adverbs', 'contrast'],
  segments: [
    buildSegment('hare-1', 'ಒಂದು ದಿನ ಮೊಲ ಆಮೆಯನ್ನು ನೋಡಿ ನಕ್ಕಿತು.', 'One day the hare laughed at the tortoise.', 500),
    buildSegment('hare-2', 'ನಾನು ತುಂಬ ಬೇಗ ಓಡುತ್ತೇನೆ ಎಂದು ಮೊಲ ಹೆಮ್ಮೆಪಟ್ಟಿತು.', 'The hare boasted that it could run very fast.', 500),
    buildSegment('hare-3', 'ಆಮೆ ಶಾಂತವಾಗಿ ನಾವು ಓಟ ಮಾಡೋಣ ಎಂದು ಹೇಳಿತು.', 'The tortoise calmly said they should have a race.', 520),
    buildSegment('hare-4', 'ಓಟ ಶುರುವಾದ ಕೂಡಲೇ ಮೊಲ ತುಂಬಾ ವೇಗವಾಗಿ ಓಡಿತು.', 'As soon as the race began, the hare ran very quickly.', 500),
    buildSegment('hare-5', 'ಆದರೆ ಆಮೆ ನಿಧಾನವಾಗಿ ನಿಲ್ಲದೆ ಮುಂದೆ ಸಾಗಿತು.', 'But the tortoise kept moving forward slowly without stopping.', 520),
    buildSegment('hare-6', 'ಮೊಲ ಮರದ ಕೆಳಗೆ ಸ್ವಲ್ಪ ನಿದ್ದೆ ಮಾಡಿತು.', 'The hare took a nap under a tree.', 540),
    buildSegment('hare-7', 'ಆಮೆ ಕೊನೆಯಲ್ಲಿ ಗುರಿಯನ್ನು ಮೊದಲು ತಲುಪಿತು.', 'In the end, the tortoise reached the finish line first.', 520),
    buildSegment('hare-8', 'ನಿಧಾನವಾದರೂ ನಿರಂತರ ಪ್ರಯತ್ನ ಗೆಲ್ಲುತ್ತದೆ.', 'Steady effort wins even when it is slow.', 540),
  ],
  inlineGlossary: [
    {
      id: 'hare-glossary-hemme',
      word: 'ಹೆಮ್ಮೆಪಟ್ಟಿತು',
      surfaceForms: ['ಹೆಮ್ಮೆಪಟ್ಟಿತು'],
      meaning: 'boasted',
      pronunciationGuide: { devanagari: 'हेम्मेपट्टितु', latin: 'hemme-pattitu' },
      note: 'Used when someone speaks proudly about themselves.',
      reviewKey: 'story:hare-and-tortoise:hemme-pattitu',
    },
    {
      id: 'hare-glossary-shanta',
      word: 'ಶಾಂತವಾಗಿ',
      surfaceForms: ['ಶಾಂತವಾಗಿ'],
      meaning: 'calmly',
      pronunciationGuide: { devanagari: 'शान्तवागि', latin: 'shaantavaagi' },
      note: 'A useful adverb for soft and steady actions.',
      reviewKey: 'story:hare-and-tortoise:shaantavaagi',
    },
    {
      id: 'hare-glossary-vegavaagi',
      word: 'ವೇಗವಾಗಿ',
      surfaceForms: ['ವೇಗವಾಗಿ', 'ಬೇಗ'],
      meaning: 'quickly / fast',
      pronunciationGuide: { devanagari: 'वेगवागि', latin: 'vegavaagi' },
      note: 'Useful for talking about speed and movement.',
      reviewKey: 'story:hare-and-tortoise:vegavaagi',
    },
    {
      id: 'hare-glossary-nillade',
      word: 'ನಿಲ್ಲದೆ',
      surfaceForms: ['ನಿಲ್ಲದೆ'],
      meaning: 'without stopping',
      pronunciationGuide: { devanagari: 'निल्लदे', latin: 'nillade' },
      note: 'A common connector for continuous action.',
      reviewKey: 'story:hare-and-tortoise:nillade',
    },
  ],
  vocabulary: [
    {
      word: 'ಹೆಮ್ಮೆಪಟ್ಟಿತು',
      meaning: 'boasted',
      pronunciation: 'hemme-pattitu',
      pronunciationGuide: { devanagari: 'हेम्मेपट्टितु', latin: 'hemme-pattitu' },
      note: 'Used when someone speaks proudly about themselves.',
      partOfSpeech: 'verb',
      reviewKey: 'story:hare-and-tortoise:hemme-pattitu',
      tags: ['emotion', 'speech'],
    },
    {
      word: 'ಶಾಂತವಾಗಿ',
      meaning: 'calmly',
      pronunciation: 'shaantavaagi',
      pronunciationGuide: { devanagari: 'शान्तवागि', latin: 'shaantavaagi' },
      note: 'A useful adverb for soft and steady actions.',
      partOfSpeech: 'adverb',
      reviewKey: 'story:hare-and-tortoise:shaantavaagi',
      tags: ['manner'],
    },
    {
      word: 'ವೇಗವಾಗಿ',
      meaning: 'quickly',
      pronunciation: 'vegavaagi',
      pronunciationGuide: { devanagari: 'वेगवागि', latin: 'vegavaagi' },
      note: 'Often used with running, speaking, or moving.',
      partOfSpeech: 'adverb',
      reviewKey: 'story:hare-and-tortoise:vegavaagi',
      tags: ['speed'],
    },
    {
      word: 'ನಿಲ್ಲದೆ',
      meaning: 'without stopping',
      pronunciation: 'nillade',
      pronunciationGuide: { devanagari: 'निल्लदे', latin: 'nillade' },
      note: 'A common connector for continuous action.',
      partOfSpeech: 'phrase',
      reviewKey: 'story:hare-and-tortoise:nillade',
      tags: ['continuity'],
    },
    {
      word: 'ನಿರಂತರ',
      meaning: 'steady / continuous',
      pronunciation: 'nirantara',
      pronunciationGuide: { devanagari: 'निरंतर', latin: 'nirantara' },
      note: 'Helpful for describing consistency and repetition.',
      partOfSpeech: 'adjective',
      reviewKey: 'story:hare-and-tortoise:nirantara',
      tags: ['consistency'],
    },
  ],
  comprehensionQuestions: [
    {
      id: 'hare-question-1',
      prompt: 'Why did the hare feel confident at the beginning of the story?',
      skill: 'detail',
      options: [
        { id: 'a', text: 'It believed it could run very fast.', isCorrect: true },
        { id: 'b', text: 'It had already won the race earlier.', isCorrect: false },
        { id: 'c', text: 'The tortoise asked it for help.', isCorrect: false },
      ],
      explanation: 'The hare boasts about its speed before the race starts.',
    },
    {
      id: 'hare-question-2',
      prompt: 'What did the tortoise do during the race?',
      skill: 'sequence',
      options: [
        { id: 'a', text: 'It stopped to sleep under a tree.', isCorrect: false },
        { id: 'b', text: 'It kept moving forward without stopping.', isCorrect: true },
        { id: 'c', text: 'It ran quickly at the very end only.', isCorrect: false },
      ],
      explanation: 'The tortoise wins by continuing steadily without pausing.',
    },
    {
      id: 'hare-question-3',
      prompt: 'What idea does the story teach?',
      skill: 'moral',
      options: [
        { id: 'a', text: 'Speed matters more than effort.', isCorrect: false },
        { id: 'b', text: 'Steady effort can win.', isCorrect: true },
        { id: 'c', text: 'Sleeping during work is always good.', isCorrect: false },
      ],
      explanation: 'The ending emphasizes that steady effort beats careless speed.',
    },
  ],
};
