import { Story } from '../../types/story';
import { buildSegment } from '../story-helpers';

export const lionAndMouseStory: Story = {
  id: 'lion-and-mouse',
  slug: 'lion-and-mouse',
  title: 'ಸಿಂಹ ಮತ್ತು ಇಲಿ',
  sourceTitle: 'The Lion and the Mouse',
  sourceLabel: 'Aesop • Familiar Story',
  level: 'Beginner',
  estimatedMinutes: 3,
  summary: 'A short story built around kindness, apology, and unexpected help, with simple verbs and concrete imagery.',
  corpus: 'Aesop',
  themeTags: ['animals', 'kindness', 'friendship'],
  grammarFocus: ['simple past', 'requests', 'cause and effect'],
  segments: [
    buildSegment('lion-1', 'ಒಂದು ದೊಡ್ಡ ಸಿಂಹ ಕಾಡಿನಲ್ಲಿ ಮಲಗಿತ್ತು.', 'A big lion was sleeping in the forest.', 520),
    buildSegment('lion-2', 'ಚಿಕ್ಕ ಇಲಿ ಅದರ ಮೇಲಿಂದ ಓಡಿತು.', 'A small mouse ran across it.', 520),
    buildSegment('lion-3', 'ಸಿಂಹ ಎಚ್ಚರವಾಗಿ ಇಲಿಯನ್ನು ಹಿಡಿತು.', 'The lion woke up and caught the mouse.', 520),
    buildSegment('lion-4', 'ದಯವಿಟ್ಟು ನನ್ನನ್ನು ಬಿಡಿ ಎಂದು ಇಲಿ ಬೇಡಿಕೊಂಡಿತು.', 'The mouse begged, “Please let me go.”', 520),
    buildSegment('lion-5', 'ಒಂದು ದಿನ ನಾನು ನಿಮಗೆ ಸಹಾಯ ಮಾಡಬಹುದು ಎಂದು ಅದು ಹೇಳಿತು.', 'It said that one day it might help the lion.', 520),
    buildSegment('lion-6', 'ನಂತರ ಸಿಂಹ ಬಲೆಗೆ ಸಿಕ್ಕಿತು ಮತ್ತು ಗರ್ಜಿಸಿತು.', 'Later the lion was trapped in a net and roared.', 540),
    buildSegment('lion-7', 'ಇಲಿ ಬಂದು ಕಗ್ಗಂಟನ್ನು ಕಚ್ಚಿ ಸಿಂಹವನ್ನು ಬಿಡಿಸಿತು.', 'The mouse came, gnawed the ropes, and freed the lion.', 540),
    buildSegment('lion-8', 'ಚಿಕ್ಕವನಾದರೂ ಒಳ್ಳೆಯ ಸ್ನೇಹಿತ ಸಹಾಯ ಮಾಡಬಹುದು.', 'Even someone small can be a good friend and help.', 540),
  ],
  inlineGlossary: [
    {
      id: 'lion-glossary-eccharavaagi',
      word: 'ಎಚ್ಚರವಾಗಿ',
      surfaceForms: ['ಎಚ್ಚರವಾಗಿ'],
      meaning: 'woke up / became alert',
      pronunciationGuide: { devanagari: 'एच्चरवागि', latin: 'eccharavaagi' },
      note: 'Useful for moving from sleep to attention.',
      reviewKey: 'story:lion-and-mouse:eccharavaagi',
    },
    {
      id: 'lion-glossary-bedikonditu',
      word: 'ಬೇಡಿಕೊಂಡಿತು',
      surfaceForms: ['ಬೇಡಿಕೊಂಡಿತು'],
      meaning: 'begged',
      pronunciationGuide: { devanagari: 'बेडिकोंडितु', latin: 'bedikonditu' },
      note: 'Common in polite or desperate requests.',
      reviewKey: 'story:lion-and-mouse:bedikonditu',
    },
    {
      id: 'lion-glossary-bale',
      word: 'ಬಲೆ',
      surfaceForms: ['ಬಲೆಗೆ', 'ಬಲೆ'],
      meaning: 'net / trap',
      pronunciationGuide: { devanagari: 'बले', latin: 'bale' },
      note: 'A concrete noun that appears in many folk stories.',
      reviewKey: 'story:lion-and-mouse:bale',
    },
    {
      id: 'lion-glossary-bidisitu',
      word: 'ಬಿಡಿಸಿತು',
      surfaceForms: ['ಬಿಡಿಸಿತು'],
      meaning: 'set free',
      pronunciationGuide: { devanagari: 'बिडिसितु', latin: 'bidisitu' },
      note: 'A high-value verb for rescue situations.',
      reviewKey: 'story:lion-and-mouse:bidisitu',
    },
  ],
  vocabulary: [
    {
      word: 'ಎಚ್ಚರವಾಗಿ',
      meaning: 'woke up / became alert',
      pronunciation: 'eccharavaagi',
      pronunciationGuide: { devanagari: 'एच्चरवागि', latin: 'eccharavaagi' },
      note: 'Useful for transition from sleep to attention.',
      partOfSpeech: 'adverb',
      reviewKey: 'story:lion-and-mouse:eccharavaagi',
      tags: ['attention'],
    },
    {
      word: 'ಬೇಡಿಕೊಂಡಿತು',
      meaning: 'begged',
      pronunciation: 'bedikonditu',
      pronunciationGuide: { devanagari: 'बेडिकोंडितु', latin: 'bedikonditu' },
      note: 'Common in polite or desperate requests.',
      partOfSpeech: 'verb',
      reviewKey: 'story:lion-and-mouse:bedikonditu',
      tags: ['request'],
    },
    {
      word: 'ಬಲೆ',
      meaning: 'net / trap',
      pronunciation: 'bale',
      pronunciationGuide: { devanagari: 'बले', latin: 'bale' },
      note: 'A concrete noun that appears in many folk stories.',
      partOfSpeech: 'noun',
      reviewKey: 'story:lion-and-mouse:bale',
      tags: ['objects'],
    },
    {
      word: 'ಕಗ್ಗಂಟು',
      meaning: 'rope knot / binding',
      pronunciation: 'kaggantu',
      pronunciationGuide: { devanagari: 'कग्गंटु', latin: 'kaggantu' },
      note: 'Helpful for stories involving tying or trapping.',
      partOfSpeech: 'noun',
      reviewKey: 'story:lion-and-mouse:kaggantu',
      tags: ['objects'],
    },
    {
      word: 'ಬಿಡಿಸಿತು',
      meaning: 'set free',
      pronunciation: 'bidisitu',
      pronunciationGuide: { devanagari: 'बिडिसितु', latin: 'bidisitu' },
      note: 'A high-value verb for rescue situations.',
      partOfSpeech: 'verb',
      reviewKey: 'story:lion-and-mouse:bidisitu',
      tags: ['rescue'],
    },
  ],
  comprehensionQuestions: [
    {
      id: 'lion-question-1',
      prompt: 'Why did the mouse ask the lion to let it go?',
      skill: 'detail',
      options: [
        { id: 'a', text: 'It wanted to race the lion.', isCorrect: false },
        { id: 'b', text: 'It hoped it could help the lion one day.', isCorrect: true },
        { id: 'c', text: 'It wanted the lion to follow it into the forest.', isCorrect: false },
      ],
      explanation: 'The mouse promises future help when it begs for mercy.',
    },
    {
      id: 'lion-question-2',
      prompt: 'What problem did the lion face later in the story?',
      skill: 'sequence',
      options: [
        { id: 'a', text: 'It got trapped in a net.', isCorrect: true },
        { id: 'b', text: 'It got lost during a race.', isCorrect: false },
        { id: 'c', text: 'It could not find the mouse.', isCorrect: false },
      ],
      explanation: 'The turning point is the lion getting stuck in a trap.',
    },
    {
      id: 'lion-question-3',
      prompt: 'What lesson does the story emphasize?',
      skill: 'moral',
      options: [
        { id: 'a', text: 'Only strong animals can help others.', isCorrect: false },
        { id: 'b', text: 'Small friends can still offer meaningful help.', isCorrect: true },
        { id: 'c', text: 'Asking for help is always a weakness.', isCorrect: false },
      ],
      explanation: 'The mouse proves that size does not decide usefulness or kindness.',
    },
  ],
};
